#!/bin/bash
#
#Esse programa atualiza o repositorio do github

#Entrar no diretorio

cd /home/renato/rflinuxRepo/rflinuxRepo

#Executar comandos do git para sicronizar no repositorio github


git add .
git commit -m "script_banco_zabbix"
git commit -m "Adicionado o README.md"
git commit -m "Adicionado ao arquivo Testes"
git commit -m "criarsite.sh"
git commit -m "jenkinsfile"
git push
git status
